<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Recipe;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRandom()
    {
        $sql = "SELECT * FROM recipe ORDER BY RAND() LIMIT 1";

        $rsm = new ResultSetMapping($this->getEntityManager());
        $rsm->addEntityResult(Recipe::class, 'r');
        $rsm->addFieldResult('r', 'id', 'id');
        $rsm->addFieldResult('r', 'name', 'name');
        $rsm->addFieldResult('r', 'category', 'category');
        $rsm->addFieldResult('r', 'text', 'text');

        $query = $this->getEntityManager()->createNativeQuery($sql, $rsm);
        return $query->getOneOrNullResult();
    }
}
